//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seven_Bits_Practical.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.EmployeeSalaries = new HashSet<EmployeeSalary>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Department { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
    
        public virtual ICollection<EmployeeSalary> EmployeeSalaries { get; set; }
    }
}
