//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seven_Bits_Practical.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeSalary
    {
        public int Id { get; set; }
        public Nullable<int> EmpId { get; set; }
        public Nullable<decimal> Salary { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
